name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-docker-image:
    if: github.event_name == 'push'
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            axsleaf/felicity:latest 
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  post-changelog:
    name: Post Changelog
    runs-on: ubuntu-latest
    needs:
      build-and-push-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Changelog
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.0.0

      - name: Send Webhook
        if: ${{ success() }}
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.DISCORDHOOK_URL }}
          method: "POST"
          body: '{ "embeds": [{ "title": "Updating to v${{ steps.changelog_reader.outputs.version }}", "description": ${{ toJSON(steps.changelog_reader.outputs.changes) }}, "color": 15423743 }] }'

