name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  skip-pr:
    if: github.event_name != "push"
    runs-on: ubuntu-latest

    steps:
      - name: Skip
        run: echo "Skipping build."
        
  build-and-push-docker-image:
    if: github.event_name == "push"
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            axsleaf/felicity:latest 
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  post-changelog:
    runs-on: ubuntu-latest
    needs:
      build-and-push-docker-image
    steps:
      - name: Verify Changelog
        uses: dangoslen/changelog-enforcer@v3

      - name: Read Changelog
        if: ${{ success() }}
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.0.0

      - name: Send Webhook
        if: ${{ success() }}
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DISCORDHOOK_URL }}
          body: '{"content": null, "embeds": [{ "title": "Updating to v.${{ steps.changelog_reader.outputs.version }}", "description": "${{ steps.changelog_reader.outputs.changes }}", "color": 15423743 }], "username": "Felicity", "avatar_url": "https://whaskell.pw/images/felicity_circle.jpg", "attachments": [] }'
