name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.7.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ghcr.io/devfelicity/bot-frontend:latest
